register/register/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('scanner/', include('scanner.urls')),
    path('admin/', admin.site.urls),
]

register/scanner/urls.py
from django.urls import path

from . import views

app_name = 'scanner'

urlpatterns = [
    path('', views.index, name='index'),
    path('<uuid:history_id>/', views.purchase, name='purchase'),
    path('count_up/', views.count_up, name='count_up')
]

register/scanner/models.py
from django.db import models
import uuid

class Product(models.Model):
    product_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    product_name = models.CharField(max_length=200)
    price = models.PositiveIntegerField()
    description = models.CharField(max_length=200, blank=True)

    def __str__(self) -> str:
        return '<id : {} | name : {} | price {} | description {:20}>'.format(self.product_id,
                                                                             self.product_name,
                                                                             self.price,
                                                                             self.description)

class History(models.Model):
    history_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    purchase_date = models.DateTimeField()
    total_price = models.PositiveBigIntegerField()
    total_product = models.PositiveIntegerField()

    def __str__(self) -> str:
        return '<id {} | purchase date {} | total price {} | total product {}>'.format(self.history_id,
                                                                                       self.purchase_date,
                                                                                       self.total_price,
                                                                                       self.total_product)

class Purchase(models.Model):
    # history_id = History.history_id
    # product_id = Product.product_id
    history_id = models.ForeignKey(History, on_delete=models.CASCADE)
    product_id = models.ForeignKey(Product, on_delete=models.CASCADE)
    purchase_num = models.PositiveSmallIntegerField()

    def __str__(self) -> str:
        return '<history id {} | product id {} | purchase num {}>'.format(self.history_id,
                                                                          self.product_id,
                                                                          self.purchase_num)

register/scanner/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
from django.utils import timezone
import uuid
import json

from .models import Product, Purchase, History

# Create your views here.
def purchase(request, history_id):
    return HttpResponse("This is Purchase Page")

def count_up(request):

    history_id = uuid.UUID(request.POST.get('history_id'))
    product_id = uuid.UUID(request.POST.get('product_id'))
    history = History.objects.get(history_id=history_id)
    product = Product.objects.get(product_id=product_id)

    purchase = history.purchase_set.filter(product_id=product)
    if len(purchase):
        purchase = purchase[0]
        purchase.purchase_num += 1
        purchase.save()
    else:
        history.purchase_set.create(product_id=product, purchase_num=1)
    history.total_price += product.price
    history.total_product += 1
    history.save()

    backet = list()
    total_price = 0
    total_num = 0
    for purchase in history.purchase_set.all():
        tmp_dict = {
            'product_name':purchase.product_id.product_name,
            'price':purchase.product_id.price,
            'purchase_num':purchase.purchase_num,
            'total':purchase.product_id.price * purchase.purchase_num,
        }
        backet.append(tmp_dict)
        total_price += tmp_dict['total']
        total_num += tmp_dict['purchase_num']
    
    backet.append({
        'product_name':'',
        'price':'ごうけい',
        'purchase_num':total_num,
        'total':total_price,
    })
    
    params = {
        'backet':backet,
    }

    json_str = json.dumps(params, ensure_ascii=False, indent=2)
    return HttpResponse(json_str)

def index(request):
    history = History(purchase_date=timezone.now(), total_price=0, total_product=0)
    history.save()

    history_id = history.history_id

    backet = list()
    total_price = 0
    total_num = 0
    for purchase in history.purchase_set.all():
        tmp_dict = {
            "product_name":purchase.product_id.product_name,
            "price":purchase.product_id.price,
            "purchase_num":purchase.purchase_num,
            "total":purchase.product_id.price * purchase.purchase_num,
        }
        backet.append(tmp_dict)
        total_price += tmp_dict['total']
        total_num += tmp_dict['purchase_num']
    
    backet.append({
        "product_name":"",
        "price":"ごうけい",
        "purchase_num":total_num,
        "total":total_price,
    })

    templete = loader.get_template('scanner/index.html')
    context = {
        'history_id':history_id,
        'backet':backet,
    }
    return HttpResponse(templete.render(context, request))

register/scanner/templates/scanner/index.html
<!DOCTYPE html>
{% load static %}
{% csrf_token %}
<html lang="ja">
 <head>
 <meta charset="utf-8">
 <title>Register game</title>
 <meta name="description" content="ディスクリプションを入力">
 <meta name="viewport" content="width=device-width, initial-scale=1.0">
 <script src="{% static "qr/jsQR/dist/jsQR.js" %}"></script>
 <script src="{% static "qr/html5-qrcode/minified/html5-qrcode.min.js" %}"></script>
 <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
 <link rel="stylesheet" href="{% static 'scanner/css/index.css' %}">
</head>
<body>
<input type="hidden" value="{{history_id}}" id="history_id" class="history-id" />
<div class="title">
    <img src="{% static "scanner/image/register.png" %}" class="register-icon" />
    <h1>れじ　あぷり</h1>
</div>
<div id="reader" class="qr-reader"></div>
<div id="loadingMessage" hidden>🎥 Unable to access video stream (please make sure you have a webcam enabled)</div>
  <canvas id="canvas" hidden></canvas>
  <div id="output" hidden>
    <div id="outputMessage" hidden>No QR code detected.</div>
    <div hidden><b>Data:</b> <span id="outputData"></span></div>
  </div>
<form id="activateScanner" class="activation-form">
    <input type="submit" id="activate" value="よみとる" class="activation-botton"></input>
</form>
<div class="cart-div">
    <img src="{% static "scanner/image/cart.png" %}" class="cart" />
    <h2>かいものかご</h2>
</div>
<table id="backet" class="backet">
    <thead>
    <tr>
        <th>なまえ</th>
        <th>ねだん</th>
        <th>かず</th>
        <th>ごうけい</th>
    </tr>
    </thead>
    <tbody>

    </tbody>
</table>
<div id="list"><ul class="list-group"></ul></div>
<script>
    let html5QrcodeScanner = null
    function onScanSuccess(decodedText, decodedResult) {
    // handle the scanned code as you like, for example:
        const history_id = document.getElementById("history_id").value;
        const parsedText = JSON.parse(decodedText);
        parsedText.history_id = history_id;
        if (csrftoken == null) csrftoken = getCookie('csrftoken');
        $.ajax({
            url:"{% url 'scanner:count_up' %}",
            method:"POST",
            dataType:"json",
            data:parsedText,
        }).done(function (data, testStatus, jqXHR) {
            appendList(data.backet);
        }).fail(function(jqXHR, textStatus, errorThrown){
            alert(Object.keys(jqXHR));
            alert(jqXHR.setRequestHeader);
            alert(errorThrown);
        });
        html5QrcodeScanner.clear();
    }

    function appendList(data) {
        $('#backet').find('tbody tr').remove()
        $.each(data, function(num, data) {
            if (data.price != 'Total') {
                $('#backet>tbody').append("<tr><td>"+data.product_name+"</td><td class='number'>"+data.price+"</td><td class='number'>"+data.purchase_num+"</td><td class='number'>"+data.total+"</td></tr>")
            } else {
                $('#backet>tbody').append("<tr><td colspan='2'>"+data.price+"</td><td class='number'>"+data.purchase_num+"</td><td class='number'>"+data.total+"</td></tr>")
            }
        });
    }

    function activateScanner() {
        const config = { fps: 10, qrbox: {width: 250, height: 250} };
        html5QrcodeScanner = new Html5QrcodeScanner("reader", config, /* verbose= */ false);
        html5QrcodeScanner.render(onScanSuccess);
    }
    activateScanner();

    var video = document.createElement("video");
    var canvasElement = document.getElementById("canvas");
    var canvas = canvasElement.getContext("2d");
    var loadingMessage = document.getElementById("loadingMessage");
    var outputContainer = document.getElementById("output");
    var outputMessage = document.getElementById("outputMessage");
    var outputData = document.getElementById("outputData");


    function drawLine(begin, end, color) {
      canvas.beginPath();
      canvas.moveTo(begin.x, begin.y);
      canvas.lineTo(end.x, end.y);
      canvas.lineWidth = 4;
      canvas.strokeStyle = color;
      canvas.stroke();
    }

    // Use facingMode: environment to attemt to get the front camera on phones
    navigator.mediaDevices.getUserMedia({ video: { facingMode: "environment" } }).then(function(stream) {
    //   video.srcObject = stream;
      video.setAttribute("playsinline", true); // required to tell iOS safari we don't want fullscreen
      video.play();
      requestAnimationFrame(tick);
    });
    

    function tick() {
      loadingMessage.innerText = "⌛ Loading video..."
      if (video.readyState === video.HAVE_ENOUGH_DATA) {
        loadingMessage.hidden = true;
        canvasElement.hidden = false;
        outputContainer.hidden = false;

        canvasElement.height = video.videoHeight;
        canvasElement.width = video.videoWidth;
        canvas.drawImage(video, 0, 0, canvasElement.width, canvasElement.height);
        var imageData = canvas.getImageData(0, 0, canvasElement.width, canvasElement.height);
        var code = jsQR(imageData.data, imageData.width, imageData.height, {
          inversionAttempts: "dontInvert",
        });
        if (code) {
          drawLine(code.location.topLeftCorner, code.location.topRightCorner, "#FF3B58");
          drawLine(code.location.topRightCorner, code.location.bottomRightCorner, "#FF3B58");
          drawLine(code.location.bottomRightCorner, code.location.bottomLeftCorner, "#FF3B58");
          drawLine(code.location.bottomLeftCorner, code.location.topLeftCorner, "#FF3B58");
          outputMessage.hidden = true;
          outputData.parentElement.hidden = false;
          outputData.innerText = code.data;
        } else {
          outputMessage.hidden = false;
          outputData.parentElement.hidden = true;
        }
      }
      requestAnimationFrame(tick);
    }

    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }

    var csrftoken = getCookie('csrftoken');

    function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }

    $.ajaxSetup({
        beforeSend: function (xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
        }
    });

    $('#activateScanner').on('submit', function(e) {
        e.preventDefault();

        activateScanner();
    });

    window.onload = function() {
        {% autoescape off %}
        var backet = "{{backet}}";
        {% endautoescape %}
        var replace_backet = backet.replace('\'', '\"');
        while ( replace_backet !== backet) {
            backet = backet.replace('\'', '\"');
            replace_backet = replace_backet.replace('\'', '\"');
        }
        const backetList = JSON.parse(backet);
        appendList(backetList);
    }
    console.log(load);
  </script>
    
<footer></footer>
</body>
</html>